Repository olimorris/codecompanion.nvim, pull requests merged in 2025-09, with the labels that each got.

#1964 Support `pre_hook` option in prompt library when applicable for chat strategy.
  lua/codecompanion/strategies/init.lua
Labels: P4

#2071 Can set adapter to workflows
  doc/extending/workflows.md
  lua/codecompanion/strategies/init.lua
Labels: P4

#2101 fix(inline): Check result from vim.json.decode pcall
  lua/codecompanion/strategies/inline/init.lua
Labels: P2

#2086 feat(adapters): allow hiding of acp adapters
  doc/codecompanion.txt
  doc/configuration/adapters.md
  lua/codecompanion/config.lua
  lua/codecompanion/init.lua
Labels: P4

#2069 Fix inline adapter parsing after ACP integration
  lua/codecompanion/strategies/inline/init.lua
Labels: P2

#2106 Move chat close events to fire before clearing the buffers.
  lua/codecompanion/strategies/chat/init.lua
Labels: P4

#2016 Add floating diff layout with focus effects and workflow improvements
  doc/configuration/chat-buffer.md
  lua/codecompanion/config.lua
  lua/codecompanion/init.lua
  lua/codecompanion/providers/diff/inline.lua
  lua/codecompanion/providers/diff/split.lua
  lua/codecompanion/providers/diff/utils.lua
  lua/codecompanion/strategies/chat/acp/request_permission.lua
  lua/codecompanion/strategies/chat/edit_tracker.lua
  lua/codecompanion/strategies/chat/helpers/diff.lua
  lua/codecompanion/strategies/chat/helpers/init.lua
  lua/codecompanion/strategies/chat/helpers/super_diff.lua
  lua/codecompanion/strategies/chat/tools/catalog/insert_edit_into_file.lua
  lua/codecompanion/utils/ui.lua
  tests/config.lua
  tests/providers/diff/test_inline.lua
  tests/providers/diff/test_utils.lua
  tests/screenshots/tests-providers-diff-test_inline.lua---InlineDiff-Screenshots---Shows-floating-window-diff-for-complex-file-changes
  tests/screenshots/tests-providers-diff-test_inline.lua---InlineDiff-Screenshots---Shows-floating-window-diff-for-simple-changes
  tests/screenshots/tests-providers-diff-test_utils.lua---DiffUtils-Screenshots---Shows-complex-multi-hunk-diff-display
  tests/screenshots/tests-providers-diff-test_utils.lua---DiffUtils-Screenshots---Shows-complex-multi-hunk-highlights
  tests/screenshots/tests-providers-diff-test_utils.lua---DiffUtils-Screenshots---Shows-hunk-highlights-with-modifications
  tests/screenshots/tests-providers-diff-test_utils.lua---DiffUtils-Screenshots---Shows-unified-diff-display
  tests/screenshots/tests-utils-test_ui.lua---UI-create_float-Screenshots---Creates-new-buffer-with-content
  tests/screenshots/tests-utils-test_ui.lua---UI-create_float-Screenshots---Uses-existing-buffer-with-content-overwrite-(debug.lua-style)
  tests/screenshots/tests-utils-test_ui.lua---UI-create_float-Screenshots---Uses-existing-buffer-without-overwriting-content
  tests/strategies/chat/acp/test_permission_request.lua
  tests/utils/test_ui.lua
Labels: P3

#1678 Feature/overide default window config on open chat buffer
  doc/codecompanion.txt
  doc/usage/chat-buffer/index.md
  lua/codecompanion/init.lua
  lua/codecompanion/strategies/chat/init.lua
  lua/codecompanion/strategies/chat/keymaps.lua
  lua/codecompanion/strategies/chat/ui/init.lua
Labels: P3

#2166 fix(ui): try to append to existing winhighlight option values
  lua/codecompanion/utils/ui.lua
Labels: P4

#1827 fix(symbols): also use file contents to detect filetype
  lua/codecompanion/strategies/chat/slash_commands/helpers.lua
  lua/codecompanion/strategies/chat/slash_commands/symbols.lua
Labels: P3
