Repository olimorris/codecompanion.nvim, pull requests merged in 2025-08, with the labels that each got.

#2019 fix(tools): list code usages tool
  lua/codecompanion/strategies/chat/tools/catalog/list_code_usages/init.lua
  tests/strategies/chat/tools/catalog/list_code_usages/test_list_code_usages.lua
Labels: P2

#2020 feat(ui): fold reasoning content
  doc/configuration/others.md
  lua/codecompanion/config.lua
  lua/codecompanion/strategies/chat/ui/builder.lua
  lua/codecompanion/strategies/chat/ui/folds.lua
  lua/codecompanion/strategies/chat/ui/formatters/base.lua
  lua/codecompanion/strategies/chat/ui/formatters/reasoning.lua
  lua/codecompanion/strategies/chat/ui/formatters/standard.lua
  lua/codecompanion/strategies/chat/ui/formatters/tools.lua
  plugin/codecompanion.lua
  tests/screenshots/tests-strategies-chat-ui-test_fold_reasoning_output.lua---Reasoning-folds---creates-fold-from-header+1-to-before-Response-header
  tests/strategies/chat/ui/test_builder_state.lua
  tests/strategies/chat/ui/test_fold_reasoning_output.lua
Labels: P3

#2031 fix(diff): display the correct `sign_text` in floating diffs
  lua/codecompanion/adapters/http/copilot/helpers.lua
  lua/codecompanion/strategies/chat/debug.lua
  lua/codecompanion/strategies/chat/helpers/super_diff.lua
  lua/codecompanion/strategies/chat/keymaps.lua
  lua/codecompanion/utils/ui.lua
Labels: P4

#1988 refactor: move filter_out_messages to utils adapter
  lua/codecompanion/adapters/http/anthropic.lua
  lua/codecompanion/utils/adapters.lua
Labels: P4
